[package]
description = "Client connector to Blokli"
edition     = "2024"
homepage    = "https://hoprnet.org/"
license     = "GPL-3.0-only"
name        = "blokli-client"
repository  = "https://github.com/hoprnet/blokli"
version     = "0.4.0"

[dependencies]
async-trait = { workspace = true }
cynic = { workspace = true, features = ["http-reqwest"] }
dashmap = { workspace = true, optional = true }
eventsource-client = { workspace = true }
futures = { workspace = true }
futures-time = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true, features = [
  "brotli",
  "deflate",
  "gzip",
  "json",
  "zstd",
] }
serde_json = { workspace = true }
smart-default = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[features]
testing = ["dep:dashmap"]


[build-dependencies]
cynic-codegen = { version = "3" }

[dev-dependencies]
anyhow   = { workspace = true }
httpmock = { version = "0.8.2", features = ["record"] }
insta    = "1"
tokio    = { workspace = true }
