apiVersion: v2
name: blokli
description: Helm chart for Blokli - HOPR on-chain indexer with GraphQL API
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - blokli
  - hopr
  - blockchain
  - indexer
  - graphql
home: https://github.com/hoprnet/blokli
sources:
  - https://github.com/hoprnet/blokli
maintainers:
  - name: HOPR Team
    email: tech@hoprnet.org
