apiVersion: v2
name: blokli
description: Helm chart for Blokli - HOPR on-chain indexer with GraphQL API
type: application
icon: "https://hoprnet.org/assets/icons/logo.svg"
version: 0.1.0-rc.1
appVersion: "0.1.0"
keywords:
  - blokli
  - hopr
  - blockchain
  - indexer
  - graphql
home: https://github.com/hoprnet/blokli
sources:
  - https://github.com/hoprnet/blokli
maintainers:
  - name: HOPR Team
    email: tech@hoprnet.org
