{{- if .Values.ingress.enabled -}}
{{- $fullName := include "blokli.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hostName := .Values.ingress.hostname -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "blokli.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ required "ingress.className is required" .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ required "ingress.hostname is required" $hostName }}
      secretName: {{ $hostName | replace "." "-" | trim | trunc 60 }}-tls
  {{- end }}
  rules:
    - host: {{ required "ingress.hostname is required" $hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
