apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blokli.fullname" . }}
  labels:
    {{- include "blokli.labels" . | nindent 4 }}
type: Opaque
data:
{{- if and (eq .Values.database.type "postgresql") (not ( default false .Values.database.existingSecret)) }}
  BLOKLI_DATABASE_TYPE: {{ required "You must set .Values.database.type " .Values.database.type | b64enc | quote }}
  BLOKLI_DATABASE_URL: {{ include "blokli.databaseUrl" . | b64enc | quote }}
  BLOKLI_DATABASE_MAX_CONNECTIONS: "{{ .Values.database.maxConnections | toString | b64enc }}"
{{- end }}
  BLOKLI_RPC_URL: {{ required "config.rpcUrl is required" .Values.config.rpcUrl | b64enc | quote }}

