{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blokli.fullname" . }}
  labels:
    {{- include "blokli.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "blokli.databaseUrl" . | b64enc | quote }}
{{- end }}
