{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blokli.fullname" . }}
  labels:
    {{- include "blokli.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
{{- end }}
